### PR TITLE
IMPROVEMENT: Supported for abort exposure function

### PR DESCRIPTION
**Pull request by jctk**
Hi,

I supported for "Can't abort long exposure yet" as described in the "Limitations" section of the README has been implemented.
I have made a few modifications to my previous implementation.

Would you be willing to review this Pull Request whenever you feel like it?
I am in no hurry. Perhaps my reply to your comment is not immediate either.

Explanation of the cause of "Can't abort long exposure yet"
- The `AbortExposure` function call by the user's button operation is not made while `TimerHit` is running.
- The `AbortExposure` function is called after exiting TimerHit.
- On the other hand, `SVBGetVideData` is called repeatedly in the while loop as long as `SVBGetVideoData` times out.
- When `SVBGetVideData` is called, it may take the same amount of time as the exposure time to retrieve the image data.
- In other words, it takes the same amount of time as the exposure time to retrieve the image data for a long exposure. This behavior is executed in a while loop in the TimerHit function, which cannot be interrupted. This is why the `AbortExposure` function is not called when the Abort Exposure button is pressed during `TimerHit` execution and the exposure cannot be aborted.

Main issues to be addressed

1. Processing when timeleft is between 0.25 and 0.07 seconds in TimerHit
- In this case, set the next timer equal to the remaining time.
- By calling `SVBGetVideoData` after the exposure time has passed, I expect it to be less likely to time out.

2. Revise the while loop for image data retrieval
- I have changed from a structure that retries to retrieve image data in a while loop
- In the case of `SVB_ERROR_TIMEOUT`, set a timer and retry retrieving image data in the next call to `TimerHit`.
- This allows the `AbortExposure` function to be called after exiting `TimerHit`.
- I extended the wait for `SVBGetVideoData` from 100ms to 1000ms. I want to give `SVBGetVideoData` as long a chance as possible to retrieve image data. I set it to 1 second as the time that my feeling would allow.

3. Implement the `SV305CCD::AbortExposure` function.
- The `AbortExposure` function has not been changed.
- If the member variable `InExposure` becomes false in the `AbortExposure` function, data retrieval will not be performed by `TimerHit`.

4. Error handling other than `SVB_ERROR_TIMEOUT` in `TimerHit`'s `SVBGetVideoData` call
- Call `PrimaryCCD.setExposureFailed()` instead of `ExposureComplete()`. By calling this function, EKOS will retry to take a picture up to two times.
- Fixed a bug that when an error occurred, calling `ExposureComplete()` would cause the FITS viewer to open, assuming that the FITS buffer had been filled with data.
- Not directly related to Abort Exposure, but I corrected it because it is part of the process.

Best regard,

### CODE REVIEW

**Comment by thx8411** [comment]
Hi Sakura,

Thanks.
I'm actually on a work trip. I will look at this ASAP.

Best regards !

Blaise

**Comment by thx8411** [comment]
Hello Sakura,

Thanks ! Everything seams OK. It should be a nice improvement.
No time to test it now, perhaps the next week.

Best regards !

Blaise

**Comment by jctk** [comment]
Hello Blaise,

Thanks for the review and merge.
I look forward to you testing it next week.

Best regard,
Kakura

PS.
"Sakura" is cherry blossom in Japanese. I love it because it produces very beautiful flowers.

**Comment by thx8411** [comment]
Sorry Kakura ;-)

My daughter is a huge fan of Naruto, and she talk to me about "Sakura" every day, so, I made the mistake ;-)
I updated the driver version and the documentation files.

Kakura is your real name and  Jiacang Cheye is a nickname ?

On Internet, most of the time, my nickname is Thx8411. My "full" real name is "Blaise-Florentin Collin".
Too long...
Every body call me "Blaise".

Best regards !

Blaise

**Comment by jctk** [comment]
Hello Blaise,

I see, so it is NARUTO. It's cool.

KAKURA is my real name.
KAKURA is a rare surname in Japan, and is sometimes mistaken for SAKURA in Japan.

Japanese characters are called Kanji, which are almost the same as Chinese characters.
My full name is Jiacang Cheye in Chinese reading. This is a remnant of the name I used to use when I was working with a Chinese company about 10 years ago.

Best regards
Kakura

**Pull request merged**
